# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MockUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 500, 416))
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainMenu_pg = QtWidgets.QWidget()
        self.MainMenu_pg.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"\n"
"")
        self.MainMenu_pg.setObjectName("MainMenu_pg")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.MainMenu_pg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 501, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_4.setContentsMargins(15, 10, 15, 0)
        self.gridLayout_4.setVerticalSpacing(15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.MM_Joystick_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MM_Joystick_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.MM_Joystick_btn.setFont(font)
        self.MM_Joystick_btn.setStyleSheet("QPushButton {\n"
"border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.MM_Joystick_btn.setObjectName("MM_Joystick_btn")
        self.gridLayout_4.addWidget(self.MM_Joystick_btn, 3, 0, 1, 1)
        self.MM_Position_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MM_Position_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.MM_Position_btn.setFont(font)
        self.MM_Position_btn.setStyleSheet("QPushButton {\n"
"border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.MM_Position_btn.setObjectName("MM_Position_btn")
        self.gridLayout_4.addWidget(self.MM_Position_btn, 1, 0, 1, 1)
        self.MM_Pattern_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MM_Pattern_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.MM_Pattern_btn.setFont(font)
        self.MM_Pattern_btn.setStyleSheet("QPushButton {\n"
"border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.MM_Pattern_btn.setObjectName("MM_Pattern_btn")
        self.gridLayout_4.addWidget(self.MM_Pattern_btn, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 4, 0, 1, 1)
        self.header_MainMenu_lbl = QtWidgets.QLabel(self.MainMenu_pg)
        self.header_MainMenu_lbl.setGeometry(QtCore.QRect(0, 0, 500, 50))
        self.header_MainMenu_lbl.setMinimumSize(QtCore.QSize(0, 50))
        self.header_MainMenu_lbl.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.header_MainMenu_lbl.setFont(font)
        self.header_MainMenu_lbl.setStyleSheet("border-width: 1px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 1;\n"
"padding: 1px;\n"
"background-color: rgb(254, 254, 254);\n"
"\n"
"\n"
"")
        self.header_MainMenu_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.header_MainMenu_lbl.setObjectName("header_MainMenu_lbl")
        self.stackedWidget.addWidget(self.MainMenu_pg)
        self.BalancePosition_pg = QtWidgets.QWidget()
        self.BalancePosition_pg.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.BalancePosition_pg.setObjectName("BalancePosition_pg")
        self.gridLayoutWidget = QtWidgets.QWidget(self.BalancePosition_pg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 501, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(6, 5, 6, 0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 9, 2, 1, 1)
        self.Pos_position_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Pos_position_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pos_position_btn.setFont(font)
        self.Pos_position_btn.setStyleSheet("QPushButton {\n"
"border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.Pos_position_btn.setCheckable(True)
        self.Pos_position_btn.setObjectName("Pos_position_btn")
        self.gridLayout.addWidget(self.Pos_position_btn, 3, 3, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.Pos_center_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Pos_center_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pos_center_btn.setFont(font)
        self.Pos_center_btn.setStyleSheet("QPushButton {\n"
"border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.Pos_center_btn.setCheckable(True)
        self.Pos_center_btn.setObjectName("Pos_center_btn")
        self.gridLayout.addWidget(self.Pos_center_btn, 3, 0, 1, 3)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 5)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 7, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 8, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 7, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 8, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 4)
        self.header_Position_lbl = QtWidgets.QLabel(self.BalancePosition_pg)
        self.header_Position_lbl.setGeometry(QtCore.QRect(0, 0, 500, 50))
        self.header_Position_lbl.setMinimumSize(QtCore.QSize(0, 50))
        self.header_Position_lbl.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.header_Position_lbl.setFont(font)
        self.header_Position_lbl.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"border-width: 1px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 1;\n"
"padding: 1px;\n"
"\n"
"")
        self.header_Position_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.header_Position_lbl.setObjectName("header_Position_lbl")
        self.menu_Pos_btn = QtWidgets.QPushButton(self.BalancePosition_pg)
        self.menu_Pos_btn.setGeometry(QtCore.QRect(5, 10, 65, 28))
        self.menu_Pos_btn.setMinimumSize(QtCore.QSize(65, 0))
        self.menu_Pos_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_Pos_btn.setFont(font)
        self.menu_Pos_btn.setStyleSheet("border-width: 2px;\n"
"background-color: rgb(250, 250, 250);\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;")
        self.menu_Pos_btn.setObjectName("menu_Pos_btn")
        self.stackedWidget.addWidget(self.BalancePosition_pg)
        self.Pattern_pg = QtWidgets.QWidget()
        self.Pattern_pg.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.Pattern_pg.setObjectName("Pattern_pg")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Pattern_pg)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 60, 501, 351))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(15, 5, 15, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.Pattern_Infinity_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Pattern_Infinity_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pattern_Infinity_btn.setFont(font)
        self.Pattern_Infinity_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);")
        self.Pattern_Infinity_btn.setObjectName("Pattern_Infinity_btn")
        self.gridLayout_3.addWidget(self.Pattern_Infinity_btn, 1, 2, 1, 1)
        self.Pattern_Circle_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Pattern_Circle_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pattern_Circle_btn.setFont(font)
        self.Pattern_Circle_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);")
        self.Pattern_Circle_btn.setObjectName("Pattern_Circle_btn")
        self.gridLayout_3.addWidget(self.Pattern_Circle_btn, 1, 1, 1, 1)
        self.Pattern_Rectangle_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Pattern_Rectangle_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.Pattern_Rectangle_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pattern_Rectangle_btn.setFont(font)
        self.Pattern_Rectangle_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);")
        self.Pattern_Rectangle_btn.setObjectName("Pattern_Rectangle_btn")
        self.gridLayout_3.addWidget(self.Pattern_Rectangle_btn, 1, 0, 1, 1)
        self.Pattern_center_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Pattern_center_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pattern_center_btn.setFont(font)
        self.Pattern_center_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);")
        self.Pattern_center_btn.setObjectName("Pattern_center_btn")
        self.gridLayout_3.addWidget(self.Pattern_center_btn, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 2, 0, 1, 1)
        self.header_Pattern_lbl = QtWidgets.QLabel(self.Pattern_pg)
        self.header_Pattern_lbl.setGeometry(QtCore.QRect(0, 0, 500, 50))
        self.header_Pattern_lbl.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.header_Pattern_lbl.setFont(font)
        self.header_Pattern_lbl.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"border-width: 1px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 1;\n"
"padding: 1px;\n"
"")
        self.header_Pattern_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.header_Pattern_lbl.setObjectName("header_Pattern_lbl")
        self.menu_Pattern_btn = QtWidgets.QPushButton(self.Pattern_pg)
        self.menu_Pattern_btn.setGeometry(QtCore.QRect(5, 10, 65, 28))
        self.menu_Pattern_btn.setMinimumSize(QtCore.QSize(65, 0))
        self.menu_Pattern_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_Pattern_btn.setFont(font)
        self.menu_Pattern_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;")
        self.menu_Pattern_btn.setObjectName("menu_Pattern_btn")
        self.stackedWidget.addWidget(self.Pattern_pg)
        self.Joystick_pg = QtWidgets.QWidget()
        self.Joystick_pg.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.Joystick_pg.setObjectName("Joystick_pg")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Joystick_pg)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 501, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(6, 5, 6, 0)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 9, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 8, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setMinimumSize(QtCore.QSize(80, 0))
        self.label_17.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 8, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setMinimumSize(QtCore.QSize(80, 0))
        self.label_19.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 6, 3, 1, 1)
        self.Joystick_BallCont_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Joystick_BallCont_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Joystick_BallCont_btn.setFont(font)
        self.Joystick_BallCont_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);")
        self.Joystick_BallCont_btn.setObjectName("Joystick_BallCont_btn")
        self.gridLayout_2.addWidget(self.Joystick_BallCont_btn, 3, 0, 1, 2)
        self.Joystick_PlateCont_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Joystick_PlateCont_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Joystick_PlateCont_btn.setFont(font)
        self.Joystick_PlateCont_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: outset;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"\n"
"background-color: rgb(250, 250, 250);")
        self.Joystick_PlateCont_btn.setObjectName("Joystick_PlateCont_btn")
        self.gridLayout_2.addWidget(self.Joystick_PlateCont_btn, 3, 2, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 2, 1, 2)
        self.header_Joystick_lbl = QtWidgets.QLabel(self.Joystick_pg)
        self.header_Joystick_lbl.setGeometry(QtCore.QRect(0, 0, 500, 50))
        self.header_Joystick_lbl.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.header_Joystick_lbl.setFont(font)
        self.header_Joystick_lbl.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"border-width: 1px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 1;\n"
"padding: 1px;")
        self.header_Joystick_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.header_Joystick_lbl.setObjectName("header_Joystick_lbl")
        self.menu_Joystick_btn = QtWidgets.QPushButton(self.Joystick_pg)
        self.menu_Joystick_btn.setGeometry(QtCore.QRect(5, 10, 65, 28))
        self.menu_Joystick_btn.setMinimumSize(QtCore.QSize(65, 0))
        self.menu_Joystick_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_Joystick_btn.setFont(font)
        self.menu_Joystick_btn.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;")
        self.menu_Joystick_btn.setObjectName("menu_Joystick_btn")
        self.stackedWidget.addWidget(self.Joystick_pg)
        self.frames_lbl = QtWidgets.QLabel(self.centralwidget)
        self.frames_lbl.setGeometry(QtCore.QRect(500, 0, 300, 416))
        self.frames_lbl.setStyleSheet("border-width: 1px;\n"
"border-color: rgb(103, 103, 103);\n"
"border-style: solid;\n"
"border-radius: 2;\n"
"padding: 3px;")
        self.frames_lbl.setObjectName("frames_lbl")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MM_Joystick_btn.setText(_translate("MainWindow", "Joystick Control"))
        self.MM_Position_btn.setText(_translate("MainWindow", "Balance at Position"))
        self.MM_Pattern_btn.setText(_translate("MainWindow", "Follow a Pattern"))
        self.header_MainMenu_lbl.setText(_translate("MainWindow", "Main Menu"))
        self.label_8.setText(_translate("MainWindow", "  Y position :"))
        self.Pos_position_btn.setText(_translate("MainWindow", "Balance at position"))
        self.label_7.setText(_translate("MainWindow", "  X position :"))
        self.Pos_center_btn.setText(_translate("MainWindow", "Balance at center"))
        self.pushButton_5.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "Balance the ball in the center or select another position."))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "+"))
        self.pushButton_7.setText(_translate("MainWindow", "+"))
        self.label_5.setText(_translate("MainWindow", "Description of Balance at Center"))
        self.label_6.setText(_translate("MainWindow", "Description of Balance at Position"))
        self.label.setText(_translate("MainWindow", "Control Ball Position"))
        self.header_Position_lbl.setText(_translate("MainWindow", "Balance at a position"))
        self.menu_Pos_btn.setText(_translate("MainWindow", "Menu"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.Pattern_Infinity_btn.setText(_translate("MainWindow", "Infinity"))
        self.Pattern_Circle_btn.setText(_translate("MainWindow", "Circle"))
        self.Pattern_Rectangle_btn.setText(_translate("MainWindow", "Rectangle"))
        self.Pattern_center_btn.setText(_translate("MainWindow", "Center"))
        self.header_Pattern_lbl.setText(_translate("MainWindow", "Follow a pattern"))
        self.menu_Pattern_btn.setText(_translate("MainWindow", "Menu"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "Joystick control mode"))
        self.label_18.setText(_translate("MainWindow", "  Y angle :"))
        self.label_16.setText(_translate("MainWindow", "  X angle :"))
        self.label_17.setText(_translate("MainWindow", "\"angle\""))
        self.label_19.setText(_translate("MainWindow", "\"angle\""))
        self.Joystick_BallCont_btn.setText(_translate("MainWindow", "Control ball position"))
        self.Joystick_PlateCont_btn.setText(_translate("MainWindow", "Control plate position"))
        self.label_15.setText(_translate("MainWindow", "Describe"))
        self.label_23.setText(_translate("MainWindow", "Describe"))
        self.header_Joystick_lbl.setText(_translate("MainWindow", " Joystick Control"))
        self.menu_Joystick_btn.setText(_translate("MainWindow", "Menu"))
        self.frames_lbl.setText(_translate("MainWindow", "Label - To show Frames"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
